---
all:
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master-node:
              ansible_host: 174.129.231.212
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/master.pem
        workers:
          hosts:
            worker-node-1:
              ansible_host: 3.217.37.12
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/master.pem
    
    # Pour GitHub Actions - ex√©cution locale avec kubeconfig
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          kubeconfig_path: ~/.kube/config

  vars:
    ansible_python_interpreter: /usr/bin/python3
    k8s_version: "1.33.6"
    docker_version: "24.0"
