apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  ports:
  - port: ${APP_PORT_PATIENT}
    targetPort: ${APP_PORT_PATIENT}
    nodePort: ${NODE_PORT_PATIENT}
  selector:
    app: patient-service