apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  ports:
  - port: 8050
    targetPort: 8050
    nodePort: 30080
  selector:
    app: patient-service