spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:postgresql://localhost:5434/medecin_db
    username: medecin_user
    password: medecin_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

---
# Production profile - connects to K8s PostgreSQL service
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://doctor-db:5432/doctor_db
    username: doctor_user
    password: doctor_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect